version: '3.8'

services:
  prefect-server:
    build:
      context: .
      dockerfile: Dockerfile.prefect-server
    command: prefect server start --host 0.0.0.0
    ports:
      - '4200:4200'
    env_file:
      - .env
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL_SERVER}
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'curl -f ${PREFECT_API_URL_SERVER}/health || exit 1']
      interval: 10s
      timeout: 5s
      retries: 10

  prefect-agent:
    build: .
    env_file:
      - .env
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL_AGENT}
    restart: always
    depends_on:
      prefect-server:
        condition: service_healthy
    volumes:
      - chroma_db:/app/chroma_db

volumes:
  chroma_db:
